port: /home/akrishnan/sick_dev/netcom0
baud: 500000
scan_duration: 0.025 #no info about that in SICK-docu, but 0.025 is believable and looks good in rviz
scan_cycle_time: 0.040 #SICK-docu says S300 scans every 40ms
inverted: false
scan_id: 1
frame_id: laser_front
publish_frequency: 12
scan_intervals: [[-1.5, 1.5]] #[rad] these intervals are included to the scan
topic: /front/scan
mqtt_client: rhea_laser_front
mqtt_cmd_topic: /rhea/f0/cmd
mqtt_scan_topic: /rhea/f0/scan
mqtt_ip: localhost

